=== KatJHuang/xQueryPractice/q5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT histogram (skill*)>
<!ELEMENT skill (count+)>
<!ATTLIST skill name CDATA #REQUIRED>
<!ELEMENT count EMPTY>
<!ATTLIST count level CDATA #REQUIRED>
<!ATTLIST count n CDATA #REQUIRED>



<!--for example-->
<histogram>
	<skill name="SQL">
		<count level="1" n="5"/>
		<count level="3" n="5"/>
		<count level="4" n="5"/>
	</skill>
</histogram>

=== KatJHuang/xQueryPractice/TEMP.xml
<?xml version='1.0' standalone='no' ?>
<!DOCTYPE histogram SYSTEM 'q5.dtd'>
<histogram><skill name="SQL"><count level="1" n="0"/><count level="2" n="0"/><count level="3" n="0"/><count level="4" n="0"/><count level="5" n="2"/></skill><skill name="Scheme"><count level="1" n="0"/><count level="2" n="0"/><count level="3" n="0"/><count level="4" n="0"/><count level="5" n="2"/></skill></histogram>
